name: Publish to npm
run-name: >
  Publishing
  ${{ github.ref_name == 'main' && 'stable' || github.ref_name == 'beta' && 'beta' || github.ref_name == 'alpha' && 'alpha' || 'unknown' }}
  release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: write

env:
  node_version: 22

jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/common-test.yml
    secrets: inherit
    needs: build
    with:
      mode: build

  test_aws_cdk_lib_2_239_0:
    uses: ./.github/workflows/common-test.yml
    secrets: inherit
    needs: test
    with:
      mode: build
      awsCdk: '2.1106.1'
      awsCdkLib: '2.239.0'
      constructs: '^10.5.1'

  test_aws_cdk_lib_2_251_0:
    uses: ./.github/workflows/common-test.yml
    secrets: inherit
    needs: test_aws_cdk_lib_2_239_0
    with:
      mode: build
      awsCdk: '2.1119.0'
      awsCdkLib: '2.251.0'
      constructs: '^10.6.0'

  publish:
    needs: [test, test_aws_cdk_lib_2_239_0, test_aws_cdk_lib_2_251_0]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    concurrency:
      group: publish
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@eHawk-Inc'
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist
      - name: Semantic Release
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
